name: ANCHORE IMAGE SCAN

on: [pull_request]

jobs:
  build:
    name: Anchore Image Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the container image
        run: docker build . --file Dockerfile --tag localbuild/testimage:latest

      - uses: anchore/scan-action@v2
        with:
          image: "localbuild/testimage:latest"
          fail-build: true
          severity-cutoff: critical